language: python
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION=1.9
python:
  - "2.7"
  - "3.3"
env:
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
install:
    - pip install -q nose django-nose flake8 Django==$DJANGO_VERSION
    - pip install .

script:
    - python runtests.py
    - "flake8 . --exclude='*migrations*' --max-line-length=100"
